### ISSUE TITLE
Bug: #1

### ISSUE THREAD

**Issue by flashintv** [DJSwitchCase/TeamFortress2Bugs#2]
This whole repository is a bug :trollface:

**Comment by DJSwitchCase** [comment]
Haha it's a repository for my little uni project xd Did I name it too ambitiously to be just seen by my teacher?

**Comment by flashintv** [comment]
> Haha it's a repository for my little uni project xd Did I name it too ambitiously to be just seen by my teacher?

it's very pog 👍
